services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - DISCORD_BANK_NOTIFICATION_CHANNEL=bank_notifications

    command: python -u actual_discord_bot/bot.py

  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '12012:5006'
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
